# Generated by Django 3.2.5 on 2021-08-06 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resort',
            name='zip_code',
            field=models.CharField(max_length=50),
        ),
    ]
